### ISSUE TITLE
Nested objects in params are being "toString"-ed

### ISSUE THREAD

**Issue by jesuscript** [request/oauth-sign#11]
Hi, I found that when the querystring contains nested objects e.g. 
```
filter[email]=bob@bob.com
``` 
then the base string in hmacsign ends up with 
```
filter%3D%255Bobject%2520Object%255D
```
rather than
```
filter%255Bemail%255D%3Dbob%2540bob.com
```

I don't think this is intentional but just wanted to confirm. Let me know and I'll raise a PR.

**Comment by simov** [comment]
Closed via #16
